### ISSUE TITLE
database code 

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualistion-Framework-for-Genome-Mutations#1]
Can we please add database code to the repository.

**Comment by krassowski** [comment]
Could you explain what exactly should I add here? As for my knowledge the
code responsible for the database is already in the repository - files:
`website/models.py`, `website/db_create.py`, `website/config.py` and
`website/app.py` are related to the database. To recreate the database
please run: `cd website; mkdir databases; python3 db_create.py` (some
requirements should be met before, I will create requirements.txt soon).

2016-05-20 21:26 GMT+02:00 reimand0 <notifications@github.com>:

> Can we please add database code to the repository.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/reimandlab/Visualistion-Framework-for-Genome-Mutations/issues/1>
>



-- 
Best regards,
Michał Krassowski

**Comment by reimand0** [comment]
great! I actually did not check code before posting.

**Comment by krassowski** [comment]
So I'm happy that this explanation has helped :)

**Comment by reimand0** [comment]
i think we can close this for now. 

also learning to use this issue tracking system. looks good so far!
