### ISSUE TITLE
mutation table

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualistion-Framework-for-Genome-Mutations#3]
We should build a mutation table below the protein view. the following info for every mutation:

1. coordinate / position in sequence
2. reference AA
3. mutated AA
4. count observed in data
5. mutation type - PTM or non-PTM
6. impact on PTM - direct (on central site); flanking proximal (1-2 AA); flanking distal (3-7 AA). This is related to the closest PTM.
7. number of PTMs this mutation affects

(6-7) only shown if (5) is PTM.

We should be able to sort tables by columns and filter by value of (5).

**Comment by krassowski** [comment]
Fully implemented since c2e861870668dbd5d16682465ead20918ebfbc5b
