### ISSUE TITLE
cancer types of mutations

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualistion-Framework-for-Genome-Mutations#5]
We should update cancer type of mutations (the table column title is misleading). cancer type is actually shown in the sample_ID column field. 

For example, the first line is shown below:
comments: NA blca TCGA-BL-A0C8-01A-11D-A10S-08 1 1

BLCA is the cancer type of the first mutation (third element when separated by space). 

this is probably an enhancement of the database as well. generally cancer types are indicated by 4-letter codes and also have descriptions (BLCA is bladder urothelial carcinoma). I've copied cancer_types.txt to Dropbox for your reference.

**Comment by krassowski** [comment]
May I ask what are the two last numbers in a line (here 1 and 1)?

**Comment by reimand0** [comment]
No need to worry about these - I used these as indices in my earlier
analysis to link back to original files.
